version: '3.8'
services:

    front:
        container_name: front
        environment: 
            - VUE_APP_ISSUEADDRESS=localhost
            - VUE_APP_ISSUEPORT=4000
        build: 
            context: ./front
            dockerfile: Dockerfile
        ports: 
            - "8081:8080"
        networks: 
            - cdp
        depends_on: 
            - issues
        volumes:
            - ./front/src:/app/src
        
    issues:
        container_name: issue_server
        environment: 
            - MONGO_ISSUEADDRESS=issue_database
           
        build: 
            context: ./issues-back
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        networks:
            - cdp
        depends_on:
          - mongoIssues

    mongoIssues:
        image: mongo
        container_name: issue_database
        ports:
          - 27017:27017
        networks:
          - cdp
    
    
networks:
    cdp:
        driver: bridge